api/urls.py
from django.urls import path,include
from rest_framework.routers import SimpleRouter

from .views import  SearchListView,UserViewSet,ProductViewSet,CategoryViewSet,ProductByCategoryListView,SimilarTagsProduct,\
CategoryProductFilter,CartView,PreferencesViewSet,preference_create


app_name = 'api'

router = SimpleRouter()
#router.register('tags/<int:pk>/',SimilarTagsProduct)
router.register('category',CategoryViewSet)
router.register('users', UserViewSet)
router.register('cartview/',CartView)
router.register('preferences',PreferencesViewSet)
#router.register('search',SearchListView)
router.register('bycategory',ProductByCategoryListView)
router.register('', ProductViewSet)
urlpatterns =[
    path('',include(router.urls)),
    path('<int:category>/<str:search>/',CategoryProductFilter.as_view(),name='category_product_filter'),
    path('tags/<int:pk>/',SimilarTagsProduct.as_view(),name='tags'),
    path('createpreference/',preference_create,name='create_preference'),
  ]

#[
  #  path('users/',UserList.as_view()),
  #  path('users/<int:pk>/',UserDetail.as_view()),
  #  path('rest_auth/',include('rest_auth.urls')),
  #  path('<int:pk>/',DetailProduct.as_view()),
   # path('category/',CategoryListView.as_view()),
  #  path('api_auth/',include('rest_framework.urls')),
    
 #   path('',ListAPIView.as_view()),
    
#]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('',views.cart_detail,name='cart_detail'),
    path('add/<int:product_id>/',views.cart_add,
                                 name='cart_add'),
    path('remove/<int:product_id>/',views.cart_remove,
                                    name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.schemas import get_schema_view
from rest_framework.documentation import include_docs_urls
from rest_framework_swagger.views import get_swagger_view 

API_TITLE = 'Blog API'
API_DESCRIPTION = 'A Web API for creating and editing products.'
schema_view = get_swagger_view(title =API_TITLE)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/',include('cart.urls',namespace='cart')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('api/',include('api.urls',namespace='api')),
    path('api_auth/',include('rest_framework.urls')),
    path('api/rest-auth/', include('rest_auth.urls')),
    path('api/rest-auth/registration/', # new
                      include('rest_auth.registration.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    #path('schema/',schema_view), 
   
    path('docs/',include_docs_urls(title =API_TITLE,
                                   description=API_DESCRIPTION)),
    path('swagger-docs/',schema_view),
    path('',include('shop.urls',namespace='shop')),
   
]
if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL,
         document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views
from api.views import SearchListView ,Profile,LikedProducts,product_create,ProfileView,\
     preference_create
from rest_framework.urlpatterns import format_suffix_patterns


app_name = 'shop'

urlpatterns = [
     path('prefcret',preference_create,name='pref_cret'),
     path('filtering',views.FilterListView.as_view(),name='filter_list_view'),
     path('profileview',ProfileView.as_view(),name='profile_view'),
     #path('createproductagin',ProductCreateAPIView.as_view(),name='create_a_product_again'),
     path('createproduct/',product_create,name='create_a_product'),
     #path('createproduct/',CreateProduct.as_view(),name='create_a_product'),
     path('searchbytext/<str:query>/',views.search_by_url_text,name='search_by_url_text'),
     path('pricefilter/<int:more>/<int:less>',views.product_filter_by_price,name='price_filter'),
     path('likeaproduct/<int:pk>',views.like_create_api,name='like_thing'),
     path('likedproducts',LikedProducts.as_view(),name='liked_products'),
     path('profileapi/',Profile.as_view(),name='profile_view'),
     #path('searchapilist/',ProductSearchList.as_view(),name='product_search_list'),
   # path('api_root/'views.api_root,name='api_root'),
    #path('prodcuts/<int:pk>/highlight/',views.ProductHighlight.as_view(),name='product_highlight'), 
#     path('classproduct/',views.ProductList.as_view(),name='class_product'),
#     path('classproduct/<int:pk>/',views.ProductDetail.as_view(),name='class_productpk'), 
#     path('newdetail/<int:pk>',views.new_product_detail,name='new_product_detail'), 
#     path('listapi/',views.new_product_list,name='new_product_list'), 
   # path('searchapi/',SearchListView.as_view(),name='searchapi'), 
    path('likee/<str:product_id>/',views.like,name='likee'),
    path('like/',views.product_like,name='like'),
#     path('search1/',views.product_search,name='search_results1'),
    path('base/',views.base_view,name='base_view'),
    path('search/',views.SearchResultsListView.as_view(),
         name='search_results'),
    path('searches/',views.search_list,
         name='search_list'),
    path('new/',views.ProductCreateView.as_view(),name='product_new'),
    path('',views.product_list,name='product_list'),
    path('<slug:category_slug>/',views.product_list,
          name='product_list_by_category'),
    path('<int:id>/<slug:slug>/',views.product_detail,
         name='product_detail'),
]
urlpatterns = format_suffix_patterns(urlpatterns)

shop/forms.py
from django import forms

class SearchForm(forms.Form):
    query = forms.CharField()

class LikeForm(forms.Form):
	like = forms.BooleanField(required=True,
		                      initial=True)

shop/views.py
from django.shortcuts import render,redirect
from django.shortcuts import get_object_or_404
from .models import Category,Product
from django.views.generic import ListView,CreateView
from django.db.models import Q
from django.http import Http404
from cart.forms import CartAddProductForm
from django.db.models import Count
from rest_framework import status,mixins,generics,renderers
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.reverse import reverse 
#from django.contrib.postgres.search import TrigramSimilarity
from django.contrib.postgres.search import SearchVector,SearchQuery,SearchRank,TrigramSimilarity
from api.serializers import ProductSerializer


from rest_framework import filters

class FilterListView(generics.ListAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    filter_backends = [filters.SearchFilter]
    search_fields = ['name', 'description']



@api_view(['GET'])
def search_by_url_text(query):
    search_vector = SearchVector('name','description')
    search_query = SearchQuery(query)
    products  = Product.objects.annotate(
        similarity=TrigramSimilarity('name',query),
        ).filter(similarity__gt=0.1).order_by('-similarity')
   
    serializer = ProductSerializer(products,many=True)
    return Response(serializer.data)




@api_view(['GET'])
def product_filter_by_price(request,more,less):
    """
    List all code products,or create a new product
    """
    
    products = Product.objects.filter( price__gte=more,price__lte=less)
    #products = products.filter(price__gte=less)
    serializer = ProductSerializer(products,many=True)
    return Response(serializer.data)
     




@api_view(['POST'])
def like_create_api(request,pk):
    product = get_object_or_404(Product.objects.all(), pk=pk)
    if (request.user in product.users_like.all()):
        product.users_like.remove(request.user)
    else:
        product.users_like.add(request.user)    
    serializer = ProductSerializer(product)
    return Response(serializer.data, status=status.HTTP_201_CREATED)

# # class ProductHighlight(generics.GenericAPIView):
# #     queryset = Product.objects.all()
# #     renderer_classes = [renderers.StaticHTMLRenderer]
# #     def get(self,request,*args,**kwargs):
# #         product = self.get_object()
# #         return Response(snippet.highlishted)




# class ProductList(mixins.ListModelMixin,
#                   mixins.CreateModelMixin,
#                   generics.GenericAPIView):
#     """
#     List all product, or create a new product
#     """
#     queryset = Product.objects.all()
#     serializer_class = ProductSerializer
#     def get(self,request,*args,**kwargs):
#         #product = Product.objects.all()
#         #serializer = ProductSerializer(product,many=True)
#         #return Response(serializer.data)
#         return self.list(request,*args,**kwargs)

#     def post(self,request,format=None):
#         # serializer = ProductSerializer(data = request.data)
#         # if serializer.is_valid():
#         #     serializer.save()
#         #     return Response(serializer.data,status=status.HTTP_201_CREATED)
#         # return Response(serializer.errors, status = status.HTTP_400_BAD_REQUEST)        
#         return self.create(request,*args,**kwargs)

# class ProductDetail(mixins.RetrieveModelMixin,
#                     mixins.UpdateModelMixin,
#                     mixins.DestroyModelMixin,
#                     generics.GenericAPIView):
#     """
#     Retrieve, update or delete a  product instance 
#     """
#     queryset = Product.objects.all()
#     serializer_class = ProductSerializer

#     # def get_object(self,pk):
#     #     try:
#     #         return Product.objects.get(pk=pk)
#     #     except Product.DoesNotExist:
#     #         raise Http404


#     def get(self,request,*args,**kwargs):
#         return self.retrieve(request,*args,**kwargs)
#         # product = self.get_object(pk)
#         # serializer = ProductSerializer(product)
#         # return Response(serializer.data)

#     def put(self,request,*args,**kwargs):
#         return self.update(request,*args,**kwargs)
#         # product = self.get_object(pk)
#         # serializer = ProductSerializer(product,data=request.data)
#         # if serializer.is_valid():
#         #     serializer.save()
#         #     return Response(serializer.data)
#         # return  Response(serializer.errors,status=status.HTTP_400_BAD_REQUEST)

#     def delete(self,request,*args,**kwargs):
#         return self.destroy(request,*args,**kwargs)
#         # product = self.get_object(pk)
#         # product.delete()
#         # return Response(status=status.HTTP_204_NO_CONTENT)            





# @api_view(['GET', 'POST'])
# def new_product_list(request):
#     """
#     List all code products,or create a new product
#     """
#     if request.method == 'GET':
#         products = Product.objects.all()
#         serializer = ProductSerializer(products,many=True)
#         return Response(serializer.data)
#     elif request.method == 'POST':
#         serializer = ProductSerializer(data=request.data)
#         if serializer.is_valid():
#             serializer.save()
#             return Response(serializer.data, status = status.HTTP_201_CREATED)
#         return Response(serializer.errors , status.HTTP_400_BAD_REQUEST)        
    
        
# @api_view(['GET', 'POST', 'DELETE'])
# def new_product_detail(request,pk):
    
#     try:
#         product = Product.objects.get(pk=pk)
#     except Product.DoesNotExist:
#         return Response(status.status.HTTP_404_NOT_FOUND)

#     if request.method == 'GET':
#         serializer = ProductSerializer(product)
#         return Response(serializer.data)
#     elif request.method == 'POST':
#         serializer = ProductSerializer(product,data = request.data)
#         if serializer.is_valid():
#             serializer.save()
#             return Response(serializer.data)
#         return Response(serializer.errors,status.HTTP_400_BAD_REQUEST)
#     elif request.method == 'DELETE':
#         product.delete()
#         return Response(status=status.HTTP_204_NO_CONTENT)        




def product_list(request,category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category,slug = category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/list.html',
                  {'category':category,
                   'categories':categories,
                   'products':products})



def base_view(request):
    categories = Category.objects.all()
    return render(request,
                  'shop/base.html',
                  {'categories':categories})

from .forms import LikeForm
def like(request,product_id):
    product = Product.objects.get(id=product_id)
    form = LikeForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        if cd['like']:
          product.users_like.add(request.user)
    return redirect('shop:product_list')



def product_detail(request,id,slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    like_product_form = LikeForm()
    
    user = Product.objects.filter(users_like__username = request.user.username)
    
    liked = True 
     
    product_tags_ids = product.tags.values_list('id',flat=True)
    similar_products = Product.objects.filter(tags__in=product_tags_ids)\
                                       .exclude(id=product.id)
    similar_products = similar_products.annotate(same_tags=Count('tags'))\
                                     .order_by('-same_tags','-updated')[:4]                                    
    return render(request,
                  'shop/product/detail.html',
                  {'product':product,
                   'similar_products':similar_products,
                   'liked':liked,
                   'cart_product_form': cart_product_form,
                   'like_product_form':like_product_form})



def search_list(request,category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/search_results.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})




class SearchResultsListView(ListView):
    model = Product
    context_object_name = 'product_list'
    template_name = 'shop/product/search.html'
    def get_queryset(self):
        query = self.request.GET.get('q')
        return Product.objects.filter(
            Q(name__icontains=query) | Q(name__icontains=query)
        )

  
class ProductCreateView(CreateView):
    model = Product
    template_name = 'shop/product/product_new.html'
    fields = ('category','name','slug','image','description','price')
    def form_valid(self,form):
        form.instance.owner = self.request.user
        return super().form_valid(form)




from django.http import JsonResponse
from django.views.decorators.http import require_POST 
from django.contrib.auth.decorators import login_required

@login_required
@require_POST
def product_like(request):
    product_id = request.POST.get('id')
    action = request.POST.get('action')
    if product_id and action:
        try:
            product = Product.objects.get(id=product_id)
            if action == 'like':
                product.users_like.remove(request.user)

shop/templates/shop/product/detail.html
{% extends 'shop/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load thumbnail %}

{% block title %}
  {{ product.name }}
{% endblock %}


{% block content %}
  <div class="product-detail container" >
    <a href="{{ product.image.url }}">
      <img src="{% thumbnail product.image 300x0 quality=100 %}">
    </a>            
      <h1>{{ product.name }}</h1>
      <h2>
          <a href="{{ product.category.get_absolute_url }}">

              {{ product.category }}
          </a>
      </h2>
      <p class="price"> {{product.price}}  c.</p>
    
      




{% with total_likes=product.users_like.count users_like=product.users_like.all %}
    <div class="image-info">
      <div>
        <span class="count">
          <span class="total">{{ total_likes }}</span>
          like{{ total_likes|pluralize }}
        </span>
        <a href="#" data-id="{{ product.id }}" data-action="{% if request.user in users_like %}un{% endif %}like" class="like button">
          {% if request.user not in users_like %}
            Like
          {% else %}
            Unlike
          {% endif %}
        </a>
      </div>
      
    </div>
  {% endwith %}









      <form action="{% url 'shop:likee' product.id %}" method="post">
        {{ like_product_form }}
        {% csrf_token %}
        <button type="submit" class="btn btn-success">
         {% if liked %}
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bibi-heart" 
               viewBox="0 0 16 16">
             <path d="M8 2.748l-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
          </svg>
         {% else %}
        
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" 
               class="bi bi-heart-fill" viewBox="0 0 16 16">
             <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
          </svg>
          {% endif %}
         
        </button>
        
      </form>     
      <form action="{% url 'cart:cart_add' product.id %}" method="post">
        {{ cart_product_form }}
        {% csrf_token %}
        
        <button type="submit" class="btn btn-danger">  
          <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="#fff" class="bi bi-cart3" 
               viewBox="0 0 16 16">
                 <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
          </svg>
        </button>
      </form>

      {{ product.description|linebreaks }}
  </div>
  <div id="main" class="product-list container">
      {% for similar in similar_products %}
        <div class="item" >
            <a href="{{ similar.get_absolute_url }}">
              <img src="{%if similar.image %}{{ similar.image.url }}{% else %}
              {% static 'img/no_image.png' %}{% endif %}">
            </a>
            <a href="{{ similar.get_absolute_url }}">
                {{similar.name}}
            </a>
            <br>
            {{ similar.price }}  c.
        </div>
      
      {% endfor %}

  </div>
  
{% endblock %}


{% block domready %}
  $('a.like').click(function(e){
    e.preventDefault();
    $.post('{% url "shop:like" %}',
      {
        id: $(this).data('id'),
        action: $(this).data('action')
      },
      function(data){
        if (data['status'] == 'ok')
        {
          var previous_action = $('a.like').data('action');

          // toggle data-action
          $('a.like').data('action', previous_action == 'like' ?
          'unlike' : 'like');
          // toggle link text
          $('a.like').text(previous_action == 'like' ? 'Unlike' :
          'Like');

          // update total likes
          var previous_likes = parseInt($('span.count .total').text());
          $('span.count .total').text(previous_action == 'like' ?
          previous_likes + 1 : previous_likes - 1);
        }
      }
    );
  });
{% endblock %}

shop/templates/shop/product/list.html
{% extends 'shop/base.html' %}
{% load static %}

{% block title %}
  {% if category %}{{ category.name }}{% else %} Products {% endif %}
{% endblock %}

<!--
{% block category %}
  {% for c in categories %}
    <li>
                <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
    </li>

  {% endfor %}
{% endblock %}-->
{% block content  %}

  <!--<div id="sidebar">
      <h3>Categories</h3>
      <ul>
          <li {% if not category %} class="selected"{% endif %}>
              <a href="{% url 'shop:product_list' %}">All</a>
          </li>
          {% for c in categories %}
            <li {% if category.slug == c.slug %}class="selected"
                {% endif %}>
                <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
            </li>
          {% endfor %}
      </ul>
  </div>-->
  <div id="main" class="product-list container">
      <h1>{% if category %}
            {{ category.name }}
          {% else %}Products
          {% endif %}
      </h1>
      {% for product in products %}
        <div class="item" >
            <a href="{{ product.get_absolute_url }}">
              <img src="{%if product.image %}{{ product.image.url }}{% else %}
              {% static 'img/no_image.png' %}{% endif %}">
            </a>
            <a href="{{ product.get_absolute_url }}">
                {{product.name}}
            </a>
            <br>
            {{ product.price }}  c.
        </div>
      {% endfor %}
  </div>
{% endblock %}

shop/templates/shop/product/product_new.html
{% extends 'shop/base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block title %} new product {% endblock %}

{% block content %}
  <h2>New product nigga</h2>
  <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <button class="btn btn-success ml-2" type="submit">save it nigga</button>
  </form>
{% endblock %}

shop/templates/shop/product/search.html
{% extends 'shop/base.html' %}
{% load static %}

{% load crispy_forms_tags %}

{% block title %}
  Search
{% endblock title %}


  {% block search %}
     <div class="btn-toolbar md-3" role="toolbar" aria-label="Toolbar with button groups">
          <div class="input-group">
              <form class="input-group input-group-md"  method="get">
              <div class="input-group-prepend dropdown">
                         <button type="button"
                                 class="btn btn-default dropdown-toggle"
                                 data-toggle="dropdown"
                                 aria-haspopup="true"
                                 aria-expanded="false">
                                 All
                         </button>
                         <ul class="dropdown-menu">
                             <li>something above</li>
                             <li>something</li>
                            
                         </ul>
              </div>

              <input name='q' type="text" class="form-control" placeholder="Search" aria-label="Input group example"
                     aria-describedby="btnGroupAddon">     
              <div class="input-group-append">
                  <button  type="submit"  class="input-group-text" >
                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                      </svg>
                  </button>
              </div>
              </form>
          </div>
      </div>


  {% endblock %}
{% block content %}




  {% if query %}
    <h1> Product containing "{{ query }}"</h1>
    <h3>
      {% with results.count as total_results %}
        Found {{ total_results }} results {{ total_results|pluralize }}
      {% endwith %}
    </h3>
    {% for product in results %}
      <div class="item" >
            <a href="{{ product.get_absolute_url }}">
              <img src="{%if product.image %}{{ product.image.url }}{% else %}
              {% static 'img/no_image.png' %}{% endif %}">
            </a>
            <a href="{{ product.get_absolute_url }}">
                {{product.name}}
            </a>
            <br>
            {{ product.price }}  c.
        </div>
    {% empty %}
      <p> The are no results for your query. </p>
    {% endfor %}
      >
  {% else %}
    <h1>Search for product</h1>
   <!--  <form method="get">
      {{form|crispy}}
      <input type="submit" value="Search">
    </form>  --> 
  {% endif %} 
{% endblock content %}

shop/templates/shop/product/search_results.html
{% extends 'shop/base.html' %}
{% load static %}

{% block title %}
  {% if category %}{{ category.name }}{% else %} Products {% endif %}
{% endblock %}

{% block content  %}
  <div id="sidebar">
      <h3>Categories</h3>
      <ul>
          <li {% if not category %} class="selected"{% endif %}>
              <a href="{% url 'shop:product_list' %}">All</a>
          </li>
          {% for c in categories %}
            <li {% if category.slug == c.slug %}class="selected"
                {% endif %}>
                <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
            </li>
          {% endfor %}
      </ul>
  </div>
  <div id="main" class="product-list container">
      <h1>{% if category %}
            {{ category.name }}
          {% else %}Products
          {% endif %}
      </h1>
      {% for product in products %}
        <div class="item" >
            <a href="{{ product.get_absolute_url }}">
              <img src="{%if product.image %}{{ product.image.url }}{% else %}
              {% static 'img/no_image.png' %}{% endif %}">
            </a>
            <a href="{{ product.get_absolute_url }}">
                {{product.name}}
            </a>
            <br>
            ${{ product.price }}
        </div>
      {% endfor %}
  </div>
{% endblock %}