accounts/urls.py
from django.urls import path
from .views import user_login ,dashboard,register,edit
from django.contrib.auth import views as auth_views
app_name = 'accounts'

urlpatterns = [
    #path('profile/',ProfileView.as_view(),name='profile'),
    #path('signup/',SignUpView.as_view(),name='signup'),
    path('register/',register,name='register'),
    #path('new_login/',user_login,name='new_login'),
    path('login/',auth_views.LoginView.as_view(),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('edit/',edit,name='edit'),
    path('password_change/',
         auth_views.PasswordChangeView.as_view(),
         name='password_change'),
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),
    path('',dashboard,name='dashboard'),
]

api/urls.py
from django.urls import path,include
from rest_framework.routers import SimpleRouter

from .views import  SearchListView,UserViewSet,ProductViewSet,CategoryViewSet,ProductByCategoryListView,SimilarTagsProduct,\
CategoryProductFilter,CartView,PreferencesViewSet,preference_create


app_name = 'api'

router = SimpleRouter()
#router.register('tags/<int:pk>/',SimilarTagsProduct)
router.register('category',CategoryViewSet)
router.register('users', UserViewSet)
router.register('cartview/',CartView)
router.register('preferences',PreferencesViewSet)
#router.register('search',SearchListView)
router.register('bycategory',ProductByCategoryListView)
router.register('', ProductViewSet)
urlpatterns =[
    path('',include(router.urls)),
    path('<int:category>/<str:search>/',CategoryProductFilter.as_view(),name='category_product_filter'),
    path('tags/<int:pk>/',SimilarTagsProduct.as_view(),name='tags'),
    path('createpreference/',preference_create,name='create_preference'),
  ]

#[
  #  path('users/',UserList.as_view()),
  #  path('users/<int:pk>/',UserDetail.as_view()),
  #  path('rest_auth/',include('rest_auth.urls')),
  #  path('<int:pk>/',DetailProduct.as_view()),
   # path('category/',CategoryListView.as_view()),
  #  path('api_auth/',include('rest_framework.urls')),
    
 #   path('',ListAPIView.as_view()),
    
#]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('',views.cart_detail,name='cart_detail'),
    path('add/<int:product_id>/',views.cart_add,
                                 name='cart_add'),
    path('remove/<int:product_id>/',views.cart_remove,
                                    name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.schemas import get_schema_view
from rest_framework.documentation import include_docs_urls
from rest_framework_swagger.views import get_swagger_view 

API_TITLE = 'Blog API'
API_DESCRIPTION = 'A Web API for creating and editing products.'
schema_view = get_swagger_view(title =API_TITLE)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/',include('cart.urls',namespace='cart')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('api/',include('api.urls',namespace='api')),
    path('api_auth/',include('rest_framework.urls')),
    path('api/rest-auth/', include('rest_auth.urls')),
    path('api/rest-auth/registration/', # new
                      include('rest_auth.registration.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    #path('schema/',schema_view), 
   
    path('docs/',include_docs_urls(title =API_TITLE,
                                   description=API_DESCRIPTION)),
    path('swagger-docs/',schema_view),
    path('',include('shop.urls',namespace='shop')),
   
]
if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL,
         document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views
from api.views import SearchListView ,Profile,LikedProducts,product_create,ProfileView,\
     preference_create
from rest_framework.urlpatterns import format_suffix_patterns


app_name = 'shop'

urlpatterns = [
     path('prefcret',preference_create,name='pref_cret'),
     path('filtering',views.FilterListView.as_view(),name='filter_list_view'),
     path('profileview',ProfileView.as_view(),name='profile_view'),
     #path('createproductagin',ProductCreateAPIView.as_view(),name='create_a_product_again'),
     path('createproduct/',product_create,name='create_a_product'),
     #path('createproduct/',CreateProduct.as_view(),name='create_a_product'),
     path('searchbytext/<str:query>/',views.search_by_url_text,name='search_by_url_text'),
     path('pricefilter/<int:more>/<int:less>',views.product_filter_by_price,name='price_filter'),
     path('likeaproduct/<int:pk>',views.like_create_api,name='like_thing'),
     path('likedproducts',LikedProducts.as_view(),name='liked_products'),
     path('profileapi/',Profile.as_view(),name='profile_view'),
     #path('searchapilist/',ProductSearchList.as_view(),name='product_search_list'),
   # path('api_root/'views.api_root,name='api_root'),
    #path('prodcuts/<int:pk>/highlight/',views.ProductHighlight.as_view(),name='product_highlight'), 
#     path('classproduct/',views.ProductList.as_view(),name='class_product'),
#     path('classproduct/<int:pk>/',views.ProductDetail.as_view(),name='class_productpk'), 
#     path('newdetail/<int:pk>',views.new_product_detail,name='new_product_detail'), 
#     path('listapi/',views.new_product_list,name='new_product_list'), 
   # path('searchapi/',SearchListView.as_view(),name='searchapi'), 
    path('likee/<str:product_id>/',views.like,name='likee'),
    path('like/',views.product_like,name='like'),
#     path('search1/',views.product_search,name='search_results1'),
    path('base/',views.base_view,name='base_view'),
    path('search/',views.SearchResultsListView.as_view(),
         name='search_results'),
    path('searches/',views.search_list,
         name='search_list'),
    path('new/',views.ProductCreateView.as_view(),name='product_new'),
    path('',views.product_list,name='product_list'),
    path('<slug:category_slug>/',views.product_list,
          name='product_list_by_category'),
    path('<int:id>/<slug:slug>/',views.product_detail,
         name='product_detail'),
]
urlpatterns = format_suffix_patterns(urlpatterns)

shop/forms.py
from django import forms

class SearchForm(forms.Form):
    query = forms.CharField()

class LikeForm(forms.Form):
	like = forms.BooleanField(required=True,
		                      initial=True)

shop/views.py
from django.shortcuts import render,redirect
from django.shortcuts import get_object_or_404
from .models import Category,Product
from django.views.generic import ListView,CreateView
from django.db.models import Q
from django.http import Http404
from cart.forms import CartAddProductForm
from django.db.models import Count
from rest_framework import status,mixins,generics,renderers
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.reverse import reverse 
#from django.contrib.postgres.search import TrigramSimilarity
from django.contrib.postgres.search import SearchVector,SearchQuery,SearchRank,TrigramSimilarity
from api.serializers import ProductSerializer


from rest_framework import filters

class FilterListView(generics.ListAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    filter_backends = [filters.SearchFilter]
    search_fields = ['name', 'description']



@api_view(['GET'])
def search_by_url_text(query):
    search_vector = SearchVector('name','description')
    search_query = SearchQuery(query)
    products  = Product.objects.annotate(
        similarity=TrigramSimilarity('name',query),
        ).filter(similarity__gt=0.1).order_by('-similarity')
   
    serializer = ProductSerializer(products,many=True)
    return Response(serializer.data)




@api_view(['GET'])
def product_filter_by_price(request,more,less):
    """
    List all code products,or create a new product
    """
    
    products = Product.objects.filter( price__gte=more,price__lte=less)
    #products = products.filter(price__gte=less)
    serializer = ProductSerializer(products,many=True)
    return Response(serializer.data)
     




@api_view(['POST'])
def like_create_api(request,pk):
    product = get_object_or_404(Product.objects.all(), pk=pk)
    if (request.user in product.users_like.all()):
        product.users_like.remove(request.user)
    else:
        product.users_like.add(request.user)    
    serializer = ProductSerializer(product)
    return Response(serializer.data, status=status.HTTP_201_CREATED)

# # class ProductHighlight(generics.GenericAPIView):
# #     queryset = Product.objects.all()
# #     renderer_classes = [renderers.StaticHTMLRenderer]
# #     def get(self,request,*args,**kwargs):
# #         product = self.get_object()
# #         return Response(snippet.highlishted)




# class ProductList(mixins.ListModelMixin,
#                   mixins.CreateModelMixin,
#                   generics.GenericAPIView):
#     """
#     List all product, or create a new product
#     """
#     queryset = Product.objects.all()
#     serializer_class = ProductSerializer
#     def get(self,request,*args,**kwargs):
#         #product = Product.objects.all()
#         #serializer = ProductSerializer(product,many=True)
#         #return Response(serializer.data)
#         return self.list(request,*args,**kwargs)

#     def post(self,request,format=None):
#         # serializer = ProductSerializer(data = request.data)
#         # if serializer.is_valid():
#         #     serializer.save()
#         #     return Response(serializer.data,status=status.HTTP_201_CREATED)
#         # return Response(serializer.errors, status = status.HTTP_400_BAD_REQUEST)        
#         return self.create(request,*args,**kwargs)

# class ProductDetail(mixins.RetrieveModelMixin,
#                     mixins.UpdateModelMixin,
#                     mixins.DestroyModelMixin,
#                     generics.GenericAPIView):
#     """
#     Retrieve, update or delete a  product instance 
#     """
#     queryset = Product.objects.all()
#     serializer_class = ProductSerializer

#     # def get_object(self,pk):
#     #     try:
#     #         return Product.objects.get(pk=pk)
#     #     except Product.DoesNotExist:
#     #         raise Http404


#     def get(self,request,*args,**kwargs):
#         return self.retrieve(request,*args,**kwargs)
#         # product = self.get_object(pk)
#         # serializer = ProductSerializer(product)
#         # return Response(serializer.data)

#     def put(self,request,*args,**kwargs):
#         return self.update(request,*args,**kwargs)
#         # product = self.get_object(pk)
#         # serializer = ProductSerializer(product,data=request.data)
#         # if serializer.is_valid():
#         #     serializer.save()
#         #     return Response(serializer.data)
#         # return  Response(serializer.errors,status=status.HTTP_400_BAD_REQUEST)

#     def delete(self,request,*args,**kwargs):
#         return self.destroy(request,*args,**kwargs)
#         # product = self.get_object(pk)
#         # product.delete()
#         # return Response(status=status.HTTP_204_NO_CONTENT)            





# @api_view(['GET', 'POST'])
# def new_product_list(request):
#     """
#     List all code products,or create a new product
#     """
#     if request.method == 'GET':
#         products = Product.objects.all()
#         serializer = ProductSerializer(products,many=True)
#         return Response(serializer.data)
#     elif request.method == 'POST':
#         serializer = ProductSerializer(data=request.data)
#         if serializer.is_valid():
#             serializer.save()
#             return Response(serializer.data, status = status.HTTP_201_CREATED)
#         return Response(serializer.errors , status.HTTP_400_BAD_REQUEST)        
    
        
# @api_view(['GET', 'POST', 'DELETE'])
# def new_product_detail(request,pk):
    
#     try:
#         product = Product.objects.get(pk=pk)
#     except Product.DoesNotExist:
#         return Response(status.status.HTTP_404_NOT_FOUND)

#     if request.method == 'GET':
#         serializer = ProductSerializer(product)
#         return Response(serializer.data)
#     elif request.method == 'POST':
#         serializer = ProductSerializer(product,data = request.data)
#         if serializer.is_valid():
#             serializer.save()
#             return Response(serializer.data)
#         return Response(serializer.errors,status.HTTP_400_BAD_REQUEST)
#     elif request.method == 'DELETE':
#         product.delete()
#         return Response(status=status.HTTP_204_NO_CONTENT)        




def product_list(request,category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category,slug = category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/list.html',
                  {'category':category,
                   'categories':categories,
                   'products':products})



def base_view(request):
    categories = Category.objects.all()
    return render(request,
                  'shop/base.html',
                  {'categories':categories})

from .forms import LikeForm
def like(request,product_id):
    product = Product.objects.get(id=product_id)
    form = LikeForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        if cd['like']:
          product.users_like.add(request.user)
    return redirect('shop:product_list')



def product_detail(request,id,slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    like_product_form = LikeForm()
    
    user = Product.objects.filter(users_like__username = request.user.username)
    
    liked = True 
     
    product_tags_ids = product.tags.values_list('id',flat=True)
    similar_products = Product.objects.filter(tags__in=product_tags_ids)\
                                       .exclude(id=product.id)
    similar_products = similar_products.annotate(same_tags=Count('tags'))\
                                     .order_by('-same_tags','-updated')[:4]                                    
    return render(request,
                  'shop/product/detail.html',
                  {'product':product,
                   'similar_products':similar_products,
                   'liked':liked,
                   'cart_product_form': cart_product_form,
                   'like_product_form':like_product_form})



def search_list(request,category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/search_results.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})




class SearchResultsListView(ListView):
    model = Product
    context_object_name = 'product_list'
    template_name = 'shop/product/search.html'
    def get_queryset(self):
        query = self.request.GET.get('q')
        return Product.objects.filter(
            Q(name__icontains=query) | Q(name__icontains=query)
        )

  
class ProductCreateView(CreateView):
    model = Product
    template_name = 'shop/product/product_new.html'
    fields = ('category','name','slug','image','description','price')
    def form_valid(self,form):
        form.instance.owner = self.request.user
        return super().form_valid(form)




from django.http import JsonResponse
from django.views.decorators.http import require_POST 
from django.contrib.auth.decorators import login_required

@login_required
@require_POST
def product_like(request):
    product_id = request.POST.get('id')
    action = request.POST.get('action')
    if product_id and action:
        try:
            product = Product.objects.get(id=product_id)
            if action == 'like':
                product.users_like.remove(request.user)

shop/templates/shop/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
      <meta charset="utf-8"/>
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width,
      initial-scale=1, shrink-to-fit=no">
      <!-- Bootstrap CSS -->
      <link rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
      <title>{% block title %}My shop{% endblock %}</title>
       <!--<link rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
            integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
            crossorigin="anonymous">-->
      <!--<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">-->
      <link href="{% static 'css/base.css' %}" rel="stylesheet">

     <!-- <style>
      .jumbotron{
       background-color:#2E2D88;
       color:white;
       }
      /* Adds borders for tabs */
     .tab-content {
    border-left: 1px solid #ddd;
    border-right: 1px solid #ddd;
    border-bottom: 1px solid #ddd;
    padding: 10px;
    }
    .nav-tabs {
    margin-bottom: 0;
}
</style>-->
  </head>
  <body>
  




  <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">

      <a class="navbar-brand " href="/"><h3>Maryam.tj</h3></a>

<!-- 
      <div class="btn-toolbar md-3" role="toolbar" aria-label="Toolbar with button groups">
          <div class="input-group">
              <form class="input-group input-group-md" action="{% url 'shop:search_results' %}" method="get">
              <div class="input-group-prepend dropdown">
                         <button type="button"
                                 class="btn btn-default dropdown-toggle"
                                 data-toggle="dropdown"
                                 aria-haspopup="true"
                                 aria-expanded="false">
                                 All
                         </button>
                         <ul class="dropdown-menu">
                             <li>something above</li>
                             {% for c in categories %}
                             <li><a href="{{ c.get_absolute_url }}">{{ c.name }}</a></li>
                             {% endfor %}
                             <li>something</li>
                            
                         </ul>
              </div>

              <input name='q' type="text" class="form-control" placeholder="Search" aria-label="Input group example"
                     aria-describedby="btnGroupAddon">
              <div class="input-group-append">
                  <button  type="submit"  class="input-group-text" >
                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                      </svg>
                  </button>
              </div>
              </form>
          </div>
      </div>
 -->
      {% block search %}
      {% endblock %} 



      <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="#fff" class="bi bi-cart3" viewBox="0 0 16 16">
         <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
      </svg>
      <div class="navbar-brand" >
        {% with total_items=cart|length %}
          {% if total_items > 0 %}
            Your cart:
            <a href="{% url 'cart:cart_detail' %}">
                {{ total_items }} item{{ total_items|pluralize }},
                ${{ cart.get_total_price }}
            </a>
          {% else %}
            Your cart has nothing in it.
          {% endif %}
        {% endwith %}
    </div>
    <a href="{% url 'accounts:dashboard' %}" class="btn btn-primary ml-2">
                    Profile
                </a>
     <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
     </button> 
    <div class="collapse navbar-collapse" id="navbarCollapse">
        {% if user.is_authenticated %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link dropdown-toggle" href="#" id="userMenu"
                       data-toggle="dropdown" aria-haspopup="true"
                       aria-expanded="false">
                       {{ user.username }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right"
                         aria-labelledby="userMenu">
                       <!--  <a class="dropdown-item"
                           href="#">
                            Change password
                        </a> -->
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'logout' %}">
                            Log Out
                        </a>
                    </div>
                </li>
            </ul>
        {% else %}
            <form class="form-inline ml-auto">
                <a href="{% url 'accounts:login' %}" class="btn btn-outline-secondary">
                    Log in
                </a>
              
               <a href="{% url 'accounts:register' %}" class="btn btn-primary ml-2">
                    Sign up
                </a>
            </form>
        {% endif %}
    </div>
  </nav>

    <div id="content">
      {% block content %}
      {% endblock %}
    </div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/js-cookie@2.2.1/src/js.cookie.min.js"></script>
  <script>
    var csrftoken = Cookies.get('csrftoken');
    function csrfSafeMethod(method) {
      // these HTTP methods do not require CSRF protection
      return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
      beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
          xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
      }
    });

    $(document).ready(function(){
      {% block domready %}
      {% endblock %}
    });
  </script>






  <div class="hello">
      <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4" stype="position:absolute;
   bottom: 0;left: 0; width; 100%;text-align: center; ">
    <a class="navbar-brand" href="/" >founder and CEO  Alimov Idibek</a>
    <div class="navbar-brand cart" style="position:relative;right:-940px; top:2px; ">

    </div>
  </nav>
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
          integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
          crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3umd/popper.min.js"
          integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
          crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
          integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
          crossorigin="anonymous"></script>
  <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>-->
  <!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>-->
  </body>
</html>